version: '2'
services:
  php:
     image: phpmyadmin/phpmyadmin
     deploy:
       resources:
         limits:
           cpus: '0.5'
           memory: 50M
     container_name: php
     restart: on-failure
     links:
       - mysql:db
     depends_on:
       - mysql

  mysql:
    image: k0st/alpine-mariadb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    container_name: mysql
    restart: on-failure
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass

  nginx:
    image: nginx:stable-alpine
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    container_name: nginx
    restart: on-failure
    ports:
      - "81:80"
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
